sudo: required
language: generic
dist: bionic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
#   - travis-build@platform-notifications.robomaker.aws.a2z.com  #Uncomment once the build passes
env:
  matrix:
  - ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="robot_ws"
  - ROS_DISTRO=dashing ROS_VERSION=2 GAZEBO_VERSION=9 WORKSPACES="simulation_ws"
  global:
  - SA_NAME=object-tracker
  - SA_PACKAGE_NAME=object_tracker_simulation
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - WORKSPACES="simulation_ws"
  - secure: OiTj2AtslvooxtxyvDyeYhWa373RYuIegCL6olGbVDJceb6Z93sI7RwiSGNxJQF8JkW/L+076XLSxO2jVVjL5JKMta10h5exjmx68NSGwGUB7QpbQPAQUD8/3Cf5NnVTxltmGWi4rcXwgFSxQQUaB3M6Y8/ghqXxbQUqmuguJ6scoNyzpmVORgbZ3mOuZVe40gGcM13SyPht746amLPV2HapxoUf9at73PTlolaxzIkws/moAuEdMeLxhtkE/NgbIZKt/9AJFaogJGGftjDQL/ZSGKrlI296qJS1fnaZXzDTyNk5+/UDOZvTyjEXkoC9BK1nMIdMgo9BXlj1sVicyhovIyAQ7AX80rqXAHsK4N/KPc2HL6zorlpmBrmh9acece9OHPKOGrF4QkThefiexVLvT8TJr7ZdLFiXopOaB/Nzrl1NNJZvhJ2GVcOzEXnLEhUjVR5ZR55ZwVb50/8LExF+bLq6W99ELAueF04PINqQZtb5goVmnOKS1Spur5wiu9F42gLRv+dJCNnDgdEc3U0mvuHJ3tIPycHKANbDsY/pquCjuzkT0a0QYnzQuY0b6yqxwPlqWP0alBUtgo9A4gnb/sWY4TWTxFNLXUKEvGlhWhe8ijg+8FNTIhRmY3qosmiYLPLLswAKbUj0T1Ski1CXCjGTcv3C+jCRZG2hJ18=
  - secure: NW37G5hIZQ5M3yj7PkrFoMfW1z+1a9mSQSqwuGwtftmtxwmjnruv4p8UMZpML/FPx/b7dvSaRqJvX03+pzzRJlOf69SG5W7+v6dEvukQbl84Nhy7qLPeXvhXMyruXwToRChyBng+OhndF4osJtD2+JLSJuLcDxBpwyAlCg853zuyrbdTMrGEvcjXr0bLou6tRUr5ZOvu+bYZqV/1YqE0nCC/+dW+wO+t21w35Y8+6ZYRLqc6p4+dJUrdukEnstv6abNAsiHptFsiIVmbLxq5v34Ytu0SFY7SOSMYFGv4EuUHyNmCyYHHk+Uueu2k7l80fWfMBLSBrT5/sRKUIUNSvtujDUqlDZ6wmsTHtqY7rrT/oPVHS0T8Ae1LABAMjR8cXxCyRFxn/euEL/0K7Je25QmzWg4MyzT/TfVW7jeA/7PqH9TmLf1+LJDgxPWM/Oe5zJlglfVmz0SX65xal6E6i8WGyY6Lfk7LZcgMB/g+8zJCL1v1t0HM+uiWIXRD98KbXJz/QzIud8DfgnWTg2xKo9FGAKv0CsyX8aYlxIR/3bK6YM8NcCg4HoAbFzy1BDXwbAybhfLBsoYO3cFRN2Ao6ns5RtQsgo2mK0202H3vfiSOKUCRkBmmabxiJHZq2Ab/J/oZ2If55Klv/qs8GCoa1BKUSpSmgt/ojKE98QY3TQQ=
before_install:
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/add_tag.sh"
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- .ros_ci/ce_build.sh
- kill %1
before_deploy:
- . .ros_ci/before_deploy.sh
